services:
  - type: web
    name: casino
    env: php
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y unzip curl libmcrypt-dev libpng-dev libjpeg-dev libfreetype6-dev \
      && docker-php-ext-configure gd --with-freetype --with-jpeg \
      && docker-php-ext-install gd pdo pdo_mysql \
      && curl -sS https://getcomposer.org/installer | php \
      && php composer.phar install --no-dev --optimize-autoloader
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
